language: ruby

rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head

cache: bundler
bundler_args: --jobs=4 --retry=3
sudo: false


before_install:
  - gem update --system

script:
  - bundle exec rake test
