#!/usr/bin/env ruby

require 'ripper'
require 'optparse'

opt = OptionParser.new

OPT = {
  formatter: :pp,
  version: nil,
}

opt.on('-f=VAL', '--formatter=VAL'){|v| OPT[:formatter] = v.to_sym}
opt.on('-v', '--version'){|v| OPT[:version] = v}

opt.parse!(ARGV)

if OPT[:version]
  require 'rpr/version'
  puts Rpr::VERSION
end

ARGV.each do |fname|
  code = File.read(fname)
  res = Ripper.sexp code

  case OPT[:formatter]
  when :pp
    require 'pp'
    pp res
  when :pry
    require 'pry'
    binding.pry(res)
  when :json
    require 'json'
    puts JSON.pretty_generate(res)
  else
    raise "#{OPT[:formatter]} is unknown formatter."
  end
end
